### ISSUE TITLE
installation 2.2.8

### ISSUE THREAD

**Issue by fpiernot** [EsupPortail/esup-ecandidat#5]
Bonjour,

Lorsque je lance le batch de déversement des PJ opi, j'obtiens le message d'erreur suivant 👍 

07:41:05.570 [pool-26-thread-1] ERROR  fr.univlorraine.ecandidat.controllers.CandidatureGestionController - Erreur WS OPI PJ - Parametres : codOpi=ECH5U4XG60, codApoPj=P35, idCandidat=14719
fr.univlorraine.ecandidat.services.siscol.SiScolException: Erreur WS OPI PJ - Parametres : codOpi=ECH5U4XG60, codApoPj=P35, idCandidat=14719
        at fr.univlorraine.ecandidat.services.siscol.SiScolApogeeWSServiceImpl.creerOpiPjViaWS(SiScolApogeeWSServiceImpl.java:1295)
        at fr.univlorraine.ecandidat.controllers.CandidatureGestionController.deversePjOpi(CandidatureGestionController.java:288)
        at fr.univlorraine.ecandidat.controllers.CandidatureGestionController.lambda$launchBatchAsyncOPIPj$6(CandidatureGestionController.java:261)
        at java.util.Vector.forEach(Vector.java:1249)
        at fr.univlorraine.ecandidat.controllers.CandidatureGestionController.launchBatchAsyncOPIPj(CandidatureGestionController.java:260)
        at fr.univlorraine.ecandidat.controllers.BatchController.runJob(BatchController.java:376)
        at fr.univlorraine.ecandidat.controllers.BatchController.lambda$checkBatchRun$2(BatchController.java:249)
        at java.util.Vector.forEach(Vector.java:1249)
        at fr.univlorraine.ecandidat.controllers.BatchController.checkBatchRun(BatchController.java:244)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.axis.AxisFault: Unmarshalling Error: cvc-elt.3.1: Attribute 'http://www.w3.org/2001/XMLSchema-instance,nil' must not appear on element '_libNomPatIndOpi', because the {nillable} property of '_libNomPatIndOpi' is false.
        at org.apache.axis.message.SOAPFaultBuilder.createFault(SOAPFaultBuilder.java:222)
        at org.apache.axis.message.SOAPFaultBuilder.endElement(SOAPFaultBuilder.java:129)
        at org.apache.axis.encoding.DeserializationContext.endElement(DeserializationContext.java:1087)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
        at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
        at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
        at org.apache.axis.handlers.soap.MustUnderstandChecker.invoke(MustUnderstandChecker.java:62)
        at org.apache.axis.client.AxisClient.invoke(AxisClient.java:206)
        at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
        at org.apache.axis.client.Call.invoke(Call.java:2767)
        at org.apache.axis.client.Call.invoke(Call.java:2443)
        at org.apache.axis.client.Call.invoke(Call.java:2366)
        at org.apache.axis.client.Call.invoke(Call.java:1812)
        at gouv.education.apogee.commun.client.ws.opipj.PjOpiMetierSoapBindingStub.recupererPiecesJustificativesOPIWS(PjOpiMetierSoapBindingStub.java:194)
        at fr.univlorraine.ecandidat.services.siscol.SiScolApogeeWSServiceImpl.creerOpiPjViaWS(SiScolApogeeWSServiceImpl.java:1291)

Pouvez vous m'aider?

Merci

**Comment by khergalant** [comment]
Bonjour,

Le problème sera corrigé dans la prochaine version.

Cordialement,

**Comment by khergalant** [comment]
Bonjour,

C'est corrigé, je clos ce ticket.

Cordialement,
